# Generated by Django 3.0.5 on 2020-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_grp', models.IntegerField(max_length=2)),
                ('division', models.CharField(max_length=4)),
            ],
        ),
    ]
