# Generated by Django 3.0.5 on 2020-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200419_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='numero_grp',
            field=models.IntegerField(default=777),
            preserve_default=False,
        ),
    ]
