# Generated by Django 3.0.5 on 2020-04-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20200420_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.grupo'),
            preserve_default=False,
        ),
    ]
