# Generated by Django 3.0.5 on 2020-04-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20200420_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='division',
            new_name='comision',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='id_div',
            new_name='id_com',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='numero_grp',
            new_name='numero_integrantes',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='division',
            new_name='comision',
        ),
        migrations.AddField(
            model_name='grupo',
            name='nombre_grp',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
